name: stock_data

profile: stock_data

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]

clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  stock_data:
    +schema: SEEDS

models:
  stock_data:
    +database: STOCK_DATA
    +materialized: table
    +schema: ""
    +static_analysis: unsafe

    raw:
      +materialized: view
      +schema: RAW

    staging:
      +materialized: view
      +schema: STAGING
      +static_analysis: unsafe

    intermediate:
      +materialized: table
      +schema: INTERMEDIATE



