"""
register_sproc.py
=================
One-time local script that:
  1. Connects to Snowflake using your local credentials / config.
  2. Creates an internal stage (if it doesn't already exist).
  3. Uploads Snowpark_API_Script.py to that stage.
  4. Registers STOCK_SPROC as a permanent Snowpark stored procedure.
  5. (Optional) Creates a daily Snowflake Task that calls STOCK_SPROC.

Run once from your terminal:
  python register_sproc.py

Prerequisites (install locally if not already present):
  pip install snowflake-snowpark-python pandas pandas_market_calendars requests

Configuration
-------------
Fill in the SNOWFLAKE_* and TARGET_* constants below, or set them as
environment variables before running.
"""

import os
import pathlib
from cryptography.hazmat.primitives import serialization
from snowflake.snowpark import Session

# ---------------------------------------------------------------------------
# ✏️  CONFIGURE THESE — or set as env vars
# ---------------------------------------------------------------------------
SNOWFLAKE_ACCOUNT   = os.getenv("SNOWFLAKE_ACCOUNT",   "YOUR_ACCOUNT")      # e.g. xy12345.us-east-1
SNOWFLAKE_USER      = os.getenv("SNOWFLAKE_USER",       "YOUR_USER")
SNOWFLAKE_ROLE      = os.getenv("SNOWFLAKE_ROLE",       "YOUR_ROLE")         # e.g. SYSADMIN
SNOWFLAKE_WAREHOUSE = os.getenv("SNOWFLAKE_WAREHOUSE",  "YOUR_WAREHOUSE")
SNOWFLAKE_DATABASE  = os.getenv("SNOWFLAKE_DATABASE",   "YOUR_DATABASE")
SNOWFLAKE_SCHEMA    = os.getenv("SNOWFLAKE_SCHEMA",     "YOUR_SCHEMA")

# Path to your RSA private key (.p8 file, unencrypted PKCS8 format)
# Generated by register_sproc.py setup — default location used here
SNOWFLAKE_PRIVATE_KEY_PATH = os.getenv(
    "SNOWFLAKE_PRIVATE_KEY_PATH",
    str(pathlib.Path.home() / ".snowflake" / "jdsmithwes_rsa_key.p8"),
)

# Destination table for stock price rows
TARGET_DATABASE = os.getenv("TARGET_DATABASE", SNOWFLAKE_DATABASE)
TARGET_SCHEMA   = os.getenv("TARGET_SCHEMA",   SNOWFLAKE_SCHEMA)
TARGET_TABLE    = os.getenv("TARGET_TABLE",    "STOCK_PRICES_DAILY")

# AlphaVantage API key — stored as a proc env var (never hard-coded in SQL)
ALPHAVANTAGE_API_KEY = os.getenv("ALPHAVANTAGE_API_KEY", "YOUR_AV_KEY")

# Optional: comma-separated tickers if you don't want auto-discovery
# Leave empty string "" to auto-discover from the target table instead
TICKERS = os.getenv("TICKERS", "")

# Stored proc + stage names
SPROC_NAME  = "STOCK_SPROC"
STAGE_NAME  = "STOCK_SPROC_STAGE"
EXTERNAL_ACCESS_INTEGRATION = "ALPHAVANTAGE_ACCESS_INTEGRATION"

# Set to True to also create a daily Snowflake Task
CREATE_TASK         = True
TASK_NAME           = "STOCK_SPROC_DAILY_TASK"
TASK_SCHEDULE       = "USING CRON 0 18 * * MON-FRI America/New_York"  # 6 PM ET weekdays

# ---------------------------------------------------------------------------
# SCRIPT PATH
# ---------------------------------------------------------------------------
SCRIPT_DIR  = pathlib.Path(__file__).parent
SPROC_FILE  = SCRIPT_DIR / "Snowpark_API_Script.py"

# ---------------------------------------------------------------------------
# PRIVATE KEY LOADER
# ---------------------------------------------------------------------------
def _load_private_key() -> bytes:
    """Read the unencrypted PKCS8 private key and return DER bytes for Snowflake."""
    key_path = pathlib.Path(SNOWFLAKE_PRIVATE_KEY_PATH)
    if not key_path.exists():
        raise FileNotFoundError(
            f"Private key not found at {key_path}.\n"
            "Re-run the key generation step or set SNOWFLAKE_PRIVATE_KEY_PATH."
        )
    with open(key_path, "rb") as f:
        private_key = serialization.load_pem_private_key(f.read(), password=None)
    return private_key.private_bytes(
        encoding=serialization.Encoding.DER,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )

# ---------------------------------------------------------------------------
# CONNECT
# ---------------------------------------------------------------------------
def build_session() -> Session:
    print("Connecting to Snowflake (key-pair auth)…")
    session = Session.builder.configs({
        "account":         SNOWFLAKE_ACCOUNT,
        "user":            SNOWFLAKE_USER,
        "private_key":     _load_private_key(),
        "role":            SNOWFLAKE_ROLE,
        "warehouse":       SNOWFLAKE_WAREHOUSE,
        "database":        SNOWFLAKE_DATABASE,
        "schema":          SNOWFLAKE_SCHEMA,
    }).create()
    # Explicitly activate the role in case the user's default_role overrides it
    session.sql(f"USE ROLE {SNOWFLAKE_ROLE}").collect()
    session.sql(f"USE WAREHOUSE {SNOWFLAKE_WAREHOUSE}").collect()
    session.sql(f"USE DATABASE {SNOWFLAKE_DATABASE}").collect()
    session.sql(f"USE SCHEMA {SNOWFLAKE_SCHEMA}").collect()
    print(f"  Connected as {SNOWFLAKE_USER} @ {SNOWFLAKE_ACCOUNT} (role: {SNOWFLAKE_ROLE})")
    return session


# ---------------------------------------------------------------------------
# STAGE
# ---------------------------------------------------------------------------
def ensure_stage(session: Session) -> None:
    print(f"Creating stage {STAGE_NAME} if not exists…")
    session.sql(
        f"CREATE STAGE IF NOT EXISTS {STAGE_NAME} "
        f"COMMENT = 'Stage for STOCK_SPROC Python handler'"
    ).collect()
    print("  Stage ready.")


# ---------------------------------------------------------------------------
# REGISTER STORED PROCEDURE
# ---------------------------------------------------------------------------
def register_sproc(session: Session) -> None:
    print(f"Uploading {SPROC_FILE.name} to stage…")
    session.file.put(
        str(SPROC_FILE),
        f"@{STAGE_NAME}/{SPROC_NAME}/",
        overwrite=True,
        auto_compress=False,
    )
    print("  Upload complete.")

    print(f"Registering stored procedure {SPROC_NAME}…")
    secret_ref = f"{TARGET_DATABASE}.{TARGET_SCHEMA}.ALPHAVANTAGE_SECRET"
    ddl = f"""
        CREATE OR REPLACE PROCEDURE {SNOWFLAKE_DATABASE}.{SNOWFLAKE_SCHEMA}.{SPROC_NAME}(
            start_date VARCHAR DEFAULT NULL,
            end_date   VARCHAR DEFAULT NULL
        )
        RETURNS VARCHAR
        LANGUAGE PYTHON
        RUNTIME_VERSION = '3.11'
        PACKAGES = ('snowflake-snowpark-python', 'pandas', 'requests')
        IMPORTS = ('@{STAGE_NAME}/{SPROC_NAME}/{SPROC_FILE.name}')
        EXTERNAL_ACCESS_INTEGRATIONS = ({EXTERNAL_ACCESS_INTEGRATION})
        SECRETS = ('alphavantage_secret' = {secret_ref})
        HANDLER = '{SPROC_FILE.stem}.run_as_sproc'
        EXECUTE AS OWNER
        ;
    """
    session.sql(ddl).collect()
    print(f"  {SPROC_NAME} registered successfully.")
    print()
    print("  Call with no args (today, trading-day guard active):")
    print(f"    CALL {SPROC_NAME}(NULL, NULL);")
    print()
    print("  Call with explicit range:")
    print(f"    CALL {SPROC_NAME}('2026-01-01', '2026-03-31');")


# ---------------------------------------------------------------------------
# OPTIONAL TASK
# ---------------------------------------------------------------------------
def create_task(session: Session) -> None:
    print(f"Creating task {TASK_NAME}…")
    session.sql(f"DROP TASK IF EXISTS {TASK_NAME}").collect()
    session.sql(f"""
        CREATE TASK {TASK_NAME}
            WAREHOUSE = {SNOWFLAKE_WAREHOUSE}
            SCHEDULE  = '{TASK_SCHEDULE}'
            COMMENT   = 'Daily trigger for STOCK_SPROC (runs weekdays at 6 PM ET)'
        AS
            CALL {SPROC_NAME}(NULL, NULL)
    """).collect()

    # Tasks are created suspended — resume it now
    session.sql(f"ALTER TASK {TASK_NAME} RESUME").collect()
    print(f"  Task {TASK_NAME} created and resumed.")
    print(f"  Schedule: {TASK_SCHEDULE}")


# ---------------------------------------------------------------------------
# MAIN
# ---------------------------------------------------------------------------
def main() -> None:
    session = build_session()
    try:
        ensure_stage(session)
        register_sproc(session)
        if CREATE_TASK:
            create_task(session)
        print("\nDone!")
    finally:
        session.close()


if __name__ == "__main__":
    main()
