create or replace TABLE STOCK_DATA.RAW.STOCK_PRICE_DATA_RAW (
	DATE DATE,
	OPEN FLOAT,
	HIGH FLOAT,
	LOW FLOAT,
	CLOSE FLOAT,
	ADJUSTED_CLOSE FLOAT,
	VOLUME NUMBER(38,0),
	DIVIDEND_AMOUNT FLOAT,
	SPLIT_COEFFICIENT FLOAT,
	TICKER VARCHAR(16777216),
	FILE_NAME VARCHAR(16777216),
	LOAD_TIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);